### ISSUE TITLE
error verifying master nodes ok

### ISSUE THREAD

**Issue by sonicwilson** [Kubeinit/kubeinit#7]
I am attempting to load this onto my supermicro. it keeps failing after the retries.

TASK [../../roles/okd : wait for master nodes to start SSH] *************************************************
task path: /root/kubeinit/kubeinit/roles/okd/tasks/configure_cluster_nodes.yml:54
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/root/.ansible/cp/72dc686b8e localhost '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<localhost> (0, b'/root\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/root/.ansible/cp/72dc686b8e localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577 && echo ansible-tmp-1598204770.388947-123039-117095049795577="` echo /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577 `" ) && sleep 0'"'"''
<localhost> (0, b'ansible-tmp-1598204770.388947-123039-117095049795577=/root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577\n', b'')
Using module file /usr/lib/python3.6/site-packages/ansible/modules/utilities/logic/wait_for.py
<localhost> PUT /root/.ansible/tmp/ansible-local-109879iagsm4yb/tmpfd6100c9 TO /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577/AnsiballZ_wait_for.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/root/.ansible/cp/72dc686b8e '[localhost]'
<localhost> (0, b'sftp> put /root/.ansible/tmp/ansible-local-109879iagsm4yb/tmpfd6100c9 /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577/AnsiballZ_wait_for.py\n', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/root/.ansible/cp/72dc686b8e localhost '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577/ /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577/AnsiballZ_wait_for.py && sleep 0'"'"''
<localhost> (0, b'', b'')
<localhost> ESTABLISH SSH CONNECTION FOR USER: root
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/root/.ansible/cp/72dc686b8e -tt localhost '/bin/sh -c '"'"'/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1598204770.388947-123039-117095049795577/AnsiballZ_wait_for.py && sleep 0'"'"''

TASK [../../roles/okd : verify that master nodes are ok] *********************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found:
cmd_res.stdout_lines | list | count == groups['okd_{{ kubeinit_deployment_role }}_nodes'] | count
FAILED - RETRYING: verify that master nodes are ok (60 retries left).
FAILED - RETRYING: verify that master nodes are ok (59 retries left).

**Comment by ccamacho** [comment]
Hi @sonicwilson thanks for testing the playbook and giving some feedback!

This looks like you don't have the latest Ansible, I rechecked this, and I'm not able to reproduce it.

What Ansible version do you have in the machine triggering ansible-playbook ... ?

You should have >= 2.9.11

I just added a pre-check task to verify this (Ill push it in another series of changes this week).

Just let me know if having latest Ansible works for you.

**Comment by sonicwilson** [comment]
Hello @ccamacho thanks for your response. Im excited to this working.
I actually had Ansible 2.9 and rollback to 2.8 to see if that was an issue after some googling. 
Ill update ansible again. the other thing i noticed is that in the kvm console okd-service-01 never shows its ip, attaching ss
![okd_vms](https://user-images.githubusercontent.com/18445597/91039768-2899fb80-e5db-11ea-913e-f06e2daa7839.jpg)

**Comment by sonicwilson** [comment]
upgraded ansible getting this now with -vvv
10.0.0.100> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.0.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o 'ProxyCommand=ssh -W %h:%p root@localhost' -o ControlPath=/root/.ansible/cp/dafc7f009a -tt 10.0.0.100 '/bin/sh -c '"'"'/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1598272321.8884208-181339-199341601216498/AnsiballZ_command.py && sleep 0'"'"''
<10.0.0.100> (1, b'\r\n{"msg": "non-zero return code", "cmd": "set -o pipefail\\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \\" Ready\\"\\n", "stdout": "", "stderr": "error: the server doesn\'t have a resource type \\"nodes\\"", "rc": 1, "start": "2020-08-24 12:32:02.303246", "end": "2020-08-24 12:32:02.464732", "delta": "0:00:00.161486", "changed": true, "failed": true, "invocation": {"module_args": {"executable": "/bin/bash", "_raw_params": "set -o pipefail\\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \\" Ready\\"\\n", "_uses_shell": true, "warn": true, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "creates": null, "removes": null, "stdin": null}}}\r\n', b'Shared connection to 10.0.0.100 closed.\r\n')
<10.0.0.100> Failed to connect to the host via ssh: Shared connection to 10.0.0.100 closed.
<10.0.0.100> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.0.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o 'ProxyCommand=ssh -W %h:%p root@localhost' -o ControlPath=/root/.ansible/cp/dafc7f009a 10.0.0.100 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598272321.8884208-181339-199341601216498/ > /dev/null 2>&1 && sleep 0'"'"''
<10.0.0.100> (0, b'', b'')
FAILED - RETRYING: verify that master nodes are ok (57 retries left).Result was: {
    "attempts": 4,
    "changed": true,
    "cmd": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \" Ready\"\n",
    "delta": "0:00:00.161486",
    "end": "2020-08-24 12:32:02.464732",
    "invocation": {
        "module_args": {
            "_raw_params": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \" Ready\"\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "retries": 61,
    "start": "2020-08-24 12:32:02.303246",
    "stderr": "error: the server doesn't have a resource type \"nodes\"",
    "stderr_lines": [
        "error: the server doesn't have a resource type \"nodes\""
    ],
    "stdout": "",
    "stdout_lines": []
}

**Comment by ccamacho** [comment]
@sonicwilson can you try again with latest master? I just did some tweaks to try to skip that issue (that should be only a warning)

**Comment by sonicwilson** [comment]
it still seem to be struggling at this part

<10.0.0.100> Failed to connect to the host via ssh: Shared connection to 10.0.0.100 closed.
<10.0.0.100> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.0.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o 'ProxyCommand=ssh -W %h:%p root@localhost' -o ControlPath=/root/.ansible/cp/dafc7f009a 10.0.0.100 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598313967.5734928-265074-61065122476569/ > /dev/null 2>&1 && sleep 0'"'"''
<10.0.0.100> (0, b'', b'')
failed: [hypervisor-01 -> 10.0.0.100] (item=okd-service-01) => {
    "ansible_loop_var": "cluster_node",
    "attempts": 60,
    "changed": true,
    "cluster_node": "okd-service-01",
    "cmd": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \" Ready\"\n",
    "delta": "0:00:00.145578",
    "end": "2020-08-25 00:06:08.136445",
    "invocation": {
        "module_args": {
            "_raw_params": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \" Ready\"\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-08-25 00:06:07.990867",
    "stderr": "No resources found",
    "stderr_lines": [
        "No resources found"
    ],
    "stdout": "",
    "stdout_lines": []
}

check the console view in kvm and the master nodes show this 

Connected to domain okd-master-01
[   ***] A start job is running for Ignition (fetch) (23min 44s / no limit)
[ 1428.355472] ignition[511]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #289
[**    ] A start job is running for Ignition (fetch) (23min 49s / no limit)
[ 1433.357203] ignition[511]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #290
[ ***  ] A start job is running for Ignition (fetch) (23min 54s / no limit)
[ 1438.358664] ignition[511]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #291
[     *] A start job is running for Ignition (fetch) (23min 59s / no limit)
[ 1443.360235] ignition[511]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #292
[ ***  ] A start job is running for Ignition (fetch) (24min 4s / no limit)
[ 1448.362437] ignition[511]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #293
[**    ] A start job is running for Ignition (fetch) (24min 9s / no limit)
[ 1453.363876] ignition[511]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #294
[   ***] A start job is running for Ignition (fetch) (24min 14s / no limit)

**Comment by ccamacho** [comment]
Checking these logs it looks like a DNS issue, in this case, do you have any extra config in the host? Like firewall rules?

**Comment by sonicwilson** [comment]
vanilla RHEL8, tried with CentOS8 with same results.
![firwallrules](https://user-images.githubusercontent.com/18445597/91445809-972dc200-e844-11ea-9f29-ee6400518c67.jpg)

**Comment by ccamacho** [comment]
@sonicwilson still unable to reproduce this error locally :(

**Comment by sonicwilson** [comment]
getting this now
TASK [../../roles/kubeinit_validations : Make sure required packages are installed] ************
task path: /root/kubeinit/kubeinit/roles/kubeinit_validations/tasks/libvirt_local_dependencies.yml:30
failed: [hypervisor-01] (item=python3-netaddr) => {
    "ansible_loop_var": "item",
    "assertion": "packages['python3-netaddr'] is defined",
    "changed": false,
    "evaluated_to": false,
    "item": "python3-netaddr",
    "msg": "Assertion failed"


but its already installed
[root@ocpbase kubeinit]# pip3 install netaddr
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: netaddr in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: importlib-resources; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from netaddr)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from importlib-resources; python_version < "3.7"->netaddr)
[root@ocpbase kubeinit]#

**Comment by sonicwilson** [comment]
still getting this
<10.0.0.100> Failed to connect to the host via ssh: Shared connection to 10.0.0.100 closed.
<10.0.0.100> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.0.100> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o 'ProxyCommand=ssh -W %h:%p root@localhost' -o ControlPath=/root/.ansible/cp/dafc7f009a 10.0.0.100 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1598968925.1284027-549887-276497161836868/ > /dev/null 2>&1 && sleep 0'"'"''
<10.0.0.100> (0, b'', b'')
FAILED - RETRYING: verify that master nodes are ok (58 retries left).Result was: {
    "attempts": 3,
    "changed": true,
    "cmd": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \" Ready\"\n",
    "delta": "0:00:48.188988",
    "end": "2020-09-01 14:02:53.741835",
    "invocation": {
        "module_args": {
            "_raw_params": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get nodes | grep master | grep \" Ready\"\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "retries": 61,
    "start": "2020-09-01 14:02:05.552847",
    "stderr": "Error from server (InternalError): an error on the server (\"\") has prevented the request from succeeding",
    "stderr_lines": [
        "Error from server (InternalError): an error on the server (\"\") has prevented the request from succeeding"
    ],
    "stdout": "",
    "stdout_lines": []

**Comment by sonicwilson** [comment]
output from okd-service-01
[root@okd-service-01 ~]# systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor prese>
   Active: active (running) since Tue 2020-09-01 14:12:04 UTC; 5h 0min ago
     Docs: man:httpd.service(8)
 Main PID: 31153 (httpd)
   Status: "Total requests: 12; Idle/Busy workers 100/0;Requests/sec: 0.000665;>
    Tasks: 213 (limit: 26213)
   Memory: 46.7M
   CGroup: /system.slice/httpd.service
           ├─31153 /usr/sbin/httpd -DFOREGROUND
           ├─31154 /usr/sbin/httpd -DFOREGROUND
           ├─31155 /usr/sbin/httpd -DFOREGROUND
           ├─31156 /usr/sbin/httpd -DFOREGROUND
           └─31157 /usr/sbin/httpd -DFOREGROUND

Sep 01 14:12:04 okd-service-01.kubeinit.local systemd[1]: Starting The Apache H>
Sep 01 14:12:04 okd-service-01.kubeinit.local systemd[1]: Started The Apache HT>
Sep 01 14:12:04 okd-service-01.kubeinit.local httpd[31153]: Server configured, >

[root@okd-service-01 ~]# ping google.com
PING google.com (172.217.9.206) 56(84) bytes of data.
64 bytes from iad30s14-in-f14.1e100.net (172.217.9.206): icmp_seq=1 ttl=114 time=16.2 ms
64 bytes from iad30s14-in-f14.1e100.net (172.217.9.206): icmp_seq=2 ttl=114 time=15.3 ms
64 bytes from iad30s14-in-f14.1e100.net (172.217.9.206): icmp_seq=3 ttl=114 time=15.4 ms
64 bytes from iad30s14-in-f14.1e100.net (172.217.9.206): icmp_seq=4 ttl=114 time=15.3 ms
64 bytes from iad30s14-in-f14.1e100.net (172.217.9.206): icmp_seq=5 ttl=114 time=15.10 ms
64 bytes from iad30s14-in-f14.1e100.net (172.217.9.206): icmp_seq=6 ttl=114 time=28.1 ms
^C
--- google.com ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 13ms
rtt min/avg/max/mdev = 15.283/17.711/28.057/4.638 ms
[root@okd-service-01 ~]# ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 bytes from 10.0.0.1: icmp_seq=1 ttl=64 time=0.307 ms
64 bytes from 10.0.0.1: icmp_seq=2 ttl=64 time=0.346 ms
^C
--- 10.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 17ms
rtt min/avg/max/mdev = 0.307/0.326/0.346/0.026 ms
[root@okd-service-01 ~]# export KUBECONFIG=~/install_dir/auth/kubeconfig
[root@okd-service-01 ~]# kubectl get nodes
NAME            STATUS   ROLES    AGE    VERSION
okd-master-01   Ready    master   168m   v1.18.3
okd-master-02   Ready    master   168m   v1.18.3
okd-master-03   Ready    master   168m   v1.18.3
[root@okd-service-01 ~]#

**Comment by sonicwilson** [comment]
seems like the ssh keys arent being copied
![image](https://user-images.githubusercontent.com/18445597/92125975-a0330c00-edcd-11ea-97d5-e90669c92dcc.png)

**Comment by sonicwilson** [comment]
![image](https://user-images.githubusercontent.com/18445597/92126822-a4abf480-edce-11ea-87d8-e77faaa7644d.png)

**Comment by ccamacho** [comment]
@sonicwilson try to connect from the hypervisor, there it should work.

```
[ccamacho@waka]$ ssh root@nyctea
Activate the web console with: systemctl enable --now cockpit.socket
Last login: Thu Sep  3 10:31:01 2020
[root@nyctea ~]# ssh core@10.0.0.3
The authenticity of host '10.0.0.3 (10.0.0.3)' can't be established.
ECDSA key fingerprint is SHA256:aTn1LCnS19Vff/tXKb7JMnktXn5GorgTbd8USNxh41g.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.0.0.3' (ECDSA) to the list of known hosts.
Fedora CoreOS 32.20200629.3.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/
Discuss: https://discussion.fedoraproject.org/c/server/coreos/
[core@okd-master-03 ~]$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
```

**Comment by sonicwilson** [comment]
successful direct from hypervisor
![image](https://user-images.githubusercontent.com/18445597/92133671-a679b600-edd6-11ea-8f49-8960c87a77ba.png)

**Comment by lapd-viosoft** [comment]
Hi all,
I got the same issue
```sh
g/master: attempt #147
[  716.327489] ignition[506]: GET error: Get "https://api-int.watata.kubeinit.local[**    ] A start job is running for Ignition (fetch) (11min 58s / no limit)
[  721.325667] ignition[506]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #148
[  721.329280] ignition[506]: GET error: Get "https://api-int.watata.kubeinit.local[   ***] A start job is running for Ignition (fetch) (12min 3s / no limit)
[  726.327613] ignition[506]: GET https://api-int.watata.kubeinit.local:22623/config/master: attempt #149
[  726.331193] ignition[506]: GET error: Get "https://api-int.watata.kubeinit.local[   ***] A start job is running for Ignition (fetch) (12min 8s / no limit)
```
I'm using docker container to deploy cluster
```sh
sudo docker run --rm -it \
    -v ~/.ssh/id_rsa:/root/.ssh/id_rsa:z \
    -v /etc/hosts:/etc/hosts \
    -v ${PWD}/inventory.ini:/root/inventory \
    kubeinit/kubeinit \
        --user root \
        -vvv -i /root/inventory \
        --become \
        --become-user root \
         -e "{ \
      'kubeinit_libvirt_external_service_interface_enabled': 'true', \
      'kubeinit_libvirt_external_service_interface': { \
        'attached': 'kiextbr0', \
        'dev': 'eth1', \
        'ip': '10.42.0.13', \
        'gateway': '10.42.0.3', \
        'netmask': '255.255.0.0' \
      } \
    }" \
    ./playbooks/okd.yml
```

My system is SuperMicro and Centos8 mininal fresh installed

**Comment by ccamacho** [comment]
Hi @lapd-viosoft thanks a lot for putting more information on this issue, I've been having issues for reproducing this, but you and @sonicwilson have the same issue and you have the same config (Centos8 minimal+Supermicro servers) I don't think the HW is an issue as the service node it's working fine.

For what I was able to see this is an issue bootstrapping the master nodes.

In your hypervisor can you check these commands and launch the deployment command again? Firewalld by default should be installed but disabled, so maybe it's something related with blocked traffic.

```
sudo dnf install firewalld
sudo systemctl enable firewalld
sudo systemctl start firewalld
sudo firewall-cmd --state
# ----Running----

# These rules should apply too the public zone
sudo firewall-cmd --add-service=http --permanent
sudo firewall-cmd --add-port=53/tcp --permanent
sudo firewall-cmd --add-port=53/udp --permanent
sudo firewall-cmd --reload
```

I'll try to find a Supermicro server and try to reproduce this.

@lapd-viosoft when you run the playbook can you run from the hypervisor `virsh console okd-master-01` when the master nodes start to be deployed? In that case, you will be able to see the actual error blocking the master nodes to be deployed correctly.

**Comment by lapd-viosoft** [comment]
Hi @ccamacho,
Thank for suggestions. After open firewall for HTTP and DNS (they are not enabled default after installing Centos8), I can go further. I'm setting up cluster with 5 workers (it took around 3 hours :( ) and and it stopped with this error
```sh
ailed: [hypervisor-01 -> 10.0.0.100] (item=okd-service-01) => {
    "ansible_loop_var": "cluster_node",
    "attempts": 60,
    "changed": true,
    "cluster_node": "okd-service-01",
    "cmd": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get csr -ojson | jq -r '.items[] | .metadata.name' | xargs oc adm certificate approve >/dev/null 2>&1; oc g$
t csr | grep Approved\n",
    "delta": "0:02:08.852030",
    "end": "2020-09-14 04:44:32.159431",
    "invocation": {
        "module_args": {
            "_raw_params": "set -o pipefail\nexport KUBECONFIG=~/install_dir/auth/kubeconfig; oc get csr -ojson | jq -r '.items[] | .metadata.name' | xargs oc adm certificate approve >/dev$
null 2>&1; oc get csr | grep Approved\n",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": "/bin/bash",
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2020-09-14 04:42:23.307401",
    "stderr": "",
    "stderr_lines": [],
"stdout": "csr-26v4j   82m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-4gbl6   87m 
   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-6v4l4   85m    kubernetes.io/kube-apiserve$
-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-b8nng   134m   kubernetes.io/kubelet-serving                 system:node:$
kd-master-03                                                   Approved,Issued\ncsr-bd4dr   75m    kubernetes.io/kubelet-serving                 system:node:okd-worker-02                   
                                Approved,Issued\ncsr-dsgcz   137m   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper  
 Approved,Issued\ncsr-hh8ll   84m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-hrr9z   $
5m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-l5c5t   134m   kubernetes.io/kube-apise$
ver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-n2nfd   137m   kubernetes.io/kube-apiserver-client-kubelet   system:se$
viceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-n82fw   86m    kubernetes.io/kubelet-serving                 system:node:okd-worker-05                
                                   Approved,Issued\ncsr-njzcd   85m    kubernetes.io/kubelet-serving                 system:node:okd-worker-03                                               
    Approved,Issued\ncsr-p5lsq   137m   kubernetes.io/kubelet-serving                 system:node:okd-master-01                                                   Approved,Issued\ncsr-prjvm 
  137m   kubernetes.io/kubelet-serving                 system:node:okd-master-02                                                   Approved,Issued\ncsr-q55c4   82m    kubernetes.io/kube-ap$
server-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued\ncsr-q76zj   85m    kubernetes.io/kubelet-serving                 system$
node:okd-worker-01                                                   Approved,Issued\ncsr-svnc7   74m    kubernetes.io/kubelet-serving                 system:node:okd-worker-04             
                                      Approved,Issued\ncsr-tbh5f   87m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstra
pper   Approved,Issued\ncsr-xjd5q   87m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
    "stdout_lines": [
        "csr-26v4j   82m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-4gbl6   87m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-6v4l4   85m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-b8nng   134m   kubernetes.io/kubelet-serving                 system:node:okd-master-03                                                   Approved,Issued",
        "csr-bd4dr   75m    kubernetes.io/kubelet-serving                 system:node:okd-worker-02                                                   Approved,Issued",
        "csr-dsgcz   137m   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-hh8ll   84m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-hrr9z   85m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-l5c5t   134m   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-n2nfd   137m   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-n82fw   86m    kubernetes.io/kubelet-serving                 system:node:okd-worker-05                                                   Approved,Issued",
        "csr-njzcd   85m    kubernetes.io/kubelet-serving                 system:node:okd-worker-03                                                   Approved,Issued",
        "csr-p5lsq   137m   kubernetes.io/kubelet-serving                 system:node:okd-master-01                                                   Approved,Issued",
        "csr-prjvm   137m   kubernetes.io/kubelet-serving                 system:node:okd-master-02                                                   Approved,Issued",
        "csr-q55c4   82m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-q76zj   85m    kubernetes.io/kubelet-serving                 system:node:okd-worker-01                                                   Approved,Issued",
        "csr-svnc7   74m    kubernetes.io/kubelet-serving                 system:node:okd-worker-04                                                   Approved,Issued",
        "csr-tbh5f   87m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued",
        "csr-xjd5q   87m    kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued"
    ]
}

PLAY RECAP **********************************************************************************************************************************************************************************
hypervisor-01              : ok=92   changed=60   unreachable=0    failed=1    skipped=10   rescued=0    ignored=4   
```

Btw, if I retry again, whole cluster will be destroyed and will be provision again. In the production mode, I think it's better to have option to retry to fix bugs/ or add new worker node.

**Comment by lapd-viosoft** [comment]
I'm not sure if it's safe to ignore these error but I'm able to login to console and all nodes are in ready state
```sh
NAME            STATUS   ROLES    AGE     VERSION
okd-master-01   Ready    master   3h23m   v1.18.3
okd-master-02   Ready    master   3h23m   v1.18.3
okd-master-03   Ready    master   3h20m   v1.18.3
okd-worker-01   Ready    worker   152m    v1.18.3
okd-worker-02   Ready    worker   141m    v1.18.3
okd-worker-03   Ready    worker   152m    v1.18.3
okd-worker-04   Ready    worker   141m    v1.18.3
okd-worker-05   Ready    worker   152m    v1.18.3
```

**Comment by ccamacho** [comment]
@lapd-viosoft nice it worked for you.
It failed in the last task validating all the crs were approved on time because in your case it took a lot of time to deploy then it just timed out.

Ill try to improve that verification when I have some free cycles, for the firewalld fix I pushed this https://github.com/Kubeinit/kubeinit/pull/19 thanks for the feedback!

**Comment by ccamacho** [comment]
@sonicwilson if you confirm these firewall changes fix your env I can close this then.

**Comment by lapd-viosoft** [comment]
Hi @ccamacho 
It's just another point (May be an improvement, on another github issue): It's great if there is an option to allow user continue to deploy the cluster after fixing few bugs, instead of destroying whole cluster and re-provision again. This improvement may bring another benefit: to allow add new worker nodes on deployed cluster.

**Comment by ccamacho** [comment]
@lapd-viosoft sure thing, so the cluster bootstrap is not an **easy process** one thing for sure is that adding more nodes can be implemented for sure. Please feel free to create an issue with the description of everything you would need, and I will translate it to the project's kanban board, again thanks for the feedback.

**Comment by sonicwilson** [comment]
sorry the firewalld ports/services were already in place
I re-ran them just to be certain. 
so im still having the same issue
![image](https://user-images.githubusercontent.com/18445597/93095540-36d6b700-f671-11ea-81f3-8442ada62dad.png)
it does this for 60 tries and then fails
never makes the worker node

**Comment by sonicwilson** [comment]
![image](https://user-images.githubusercontent.com/18445597/93113133-ccc90c80-f686-11ea-8b9d-4a594dcff6b0.png)
